LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := PrebuiltAPK
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := testkey
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
#LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)